name: Deploy to cPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      # Deploy to cPanel
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp.digistartup.uk
          ftp-username: ${{ secrets.ftp_username }}
          ftp-password: ${{ secrets.ftp_password }}
          #ftp-dir: /home4/digistar/githubcdci.digistartup.pk/
    
